# Secret для хранения файла users.xml ClickHouse с пользователями и паролями. Генерируется Helm-шаблоном из values.yaml.

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-users
type: Opaque
stringData:
  users.xml: |
    <yandex>
      <users>
{{- range .Values.users }}
        <{{ .name }}>
          <password>{{ .password }}</password>
          <profile>{{ .profile }}</profile>
          <networks>
{{- range .networks }}
            <ip>{{ . }}</ip>
{{- end }}
          </networks>
        </{{ .name }}>
{{- end }}
      </users>
    </yandex>
